"""removed name 

Revision ID: 576fcfdde52e
Revises: 
Create Date: 2023-06-21 19:32:34.011795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576fcfdde52e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
